### ISSUE TITLE
Tag a release

### ISSUE THREAD

**Issue by mkaito** [sunaku/dasht#1]
Hi!

I'm trying to write a PKGBUILD for arch linux, and I need *something* to use for the package version. Could you please tag a release so I can use that?

**Comment by sunaku** [comment]
Sure, tagged as [v1.0.0](https://github.com/sunaku/dasht/releases/tag/v1.0.0) now. :+1: Thanks!

**Comment by mkaito** [comment]
I think I'm done with the PKGBUILD. If you're an arch user, you could maintain it yourself, along with the AUR entry. Otherwise, I'll take care of it (I might have to be poked if I forget about it)

**Comment by sunaku** [comment]
I'm a [Void Linux](http://www.voidlinux.eu/) user, :smirk_cat: so if you don't mind, please maintain the Arch Linux package on my behalf. :sweat_smile:

Also, thanks for contributing. :+1: I'm glad this tool was useful enough to you to warrant packaging. :gift:

**Comment by mkaito** [comment]
Alright, I'll maintain the AUR entry. Poke me if I fall behind :stuck_out_tongue:

**Comment by mkaito** [comment]
Done: https://aur.archlinux.org/packages/dasht-git/

Feel free to mention the package in the README.

**Comment by sunaku** [comment]
Mentioned in b8e832320d4aa92683debf9ec1aa33ffb8219bfe, thanks!

By the way, I'd recommend replacing GNU BASH with **dash** in your PKGBUILD because this tool only requires a POSIX shell and because I've taken great care to develop it wholly under **dash** (not BASH). :neckbeard:

**Comment by mkaito** [comment]
Bash is what drives `sh` on Arch, in "posix mode". It's essentially feature equivalent with dash, but I think dash is a little more performant, although I'm not sure on that.

Bash is the default shell on Arch, and I'd feel hesitant of adding dash as a dependency. I'd also have to `sed` your scripts to have them explicitly call dash.

**Comment by sunaku** [comment]
Oh! :cold_sweat: I thought dash was the default shell and you were explicitly pulling in BASH. :sweat: My mistake. :boat:

**Comment by mkaito** [comment]
No worries. Feel free to poke me if anything needs to be changed. I'll keep an eye out, but I might just forget. Thanks for an awesome program :smile:

**Comment by sunaku** [comment]
@mkaito [version 1.1.0](https://github.com/sunaku/dasht/releases/tag/v1.1.0) is now released. :gift:  Please package it.

**Comment by mkaito** [comment]
I've updated `dasht-git` to use the lastest git tag for the package version. I've also published a new package `dasht` which will track releases.

Thanks for your hard work!

**Comment by sunaku** [comment]
Thanks @mkaito :sunglasses: but the PKGBUILD doesn't seem to be installing the included UNIX manpages? :cold_sweat:

**Comment by mkaito** [comment]
I knew I forgot something!

:runner:

**Comment by mkaito** [comment]
Fixed in both packages!

**Comment by sunaku** [comment]
Looks good, thanks! :+1:

**Comment by sunaku** [comment]
Hey @mkaito! :smirk_cat: Versions [1.2.0](https://github.com/sunaku/dasht/releases/tag/v1.2.0) and [2.0.0](https://github.com/sunaku/dasht/releases/tag/v2.0.0) are ready for you now. :gift:

**Comment by mkaito** [comment]
Yeah I just released 1.2.0 :stuck_out_tongue: 

I'll have the `dasht` package track the latest stable version, so I'll update it to 2.0.0, okay? Any reason for 1.2.0?

**Comment by sunaku** [comment]
I was supposed to package v1.2.0 last weekend but didn't get to it. :sweat_smile: You can skip packaging it for AUR.

**Comment by mkaito** [comment]
I had already pushed 1.2.0 to AUR, but pushed 2.0.0 afterwards. I did both as soon as I got the email notification from Github :wink:

**Comment by mkaito** [comment]
Actually, I wish Github would let me subscribe to releases only. I don't really care for emails about every single commment on every issue on the project.

**Comment by sunaku** [comment]
Oops, I didn't know you were "watching" the repo. :cold_sweat: I'll refrain from notifying you manually in this thread henceforth. :sweat_smile: Agreed, GitHub really needs a "only watch releases" feature; I suppose you could subscribe to the RSS feed instead, to avoid receiving so much email. :smirk_cat: Anyway, thanks for your diligence. :santa:

**Comment by sunaku** [comment]
@mkaito I just discovered that GitHub already provides [releases-only notifications via an RSS feed](https://github.com/sunaku/dasht/releases.atom). :relieved:

**Comment by mkaito** [comment]
That would require me to remember to check my RSS client. And that's a recipe for me never updating the package again :stuck_out_tongue:

**Comment by sunaku** [comment]
Hey @mkaito, v2.1.0 adds ZSH completions which can be installed like this:

```sh
cp etc/zsh/completions/* /usr/local/share/zsh/site-functions/
```

You may wish to update your PKGBUILD script accordingly. :smiley_cat:

**Comment by jaresty** [comment]
@mkaito It looks like the aur package hasn't been updated in a while; any chance you could publish an update with [the latest release?](https://github.com/sunaku/dasht/releases/tag/v2.2.0)

**Comment by mkaito** [comment]
Done

El 17 de febrero de 2018 3:12:12 GMT+00:00, Josh Aresty <notifications@github.com> escribió:
>@mkaito It looks like the aur package hasn't been updated in a while;
>any chance you could publish an update with [the latest
>release?](https://github.com/sunaku/dasht/releases/tag/v2.2.0) 
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/sunaku/dasht/issues/1#issuecomment-366411841

-- 
Enviado desde mi dispositivo Android con K-9 Mail. Por favor, disculpa mi brevedad.

**Comment by jaresty** [comment]
Thanks!

**Comment by sunaku** [comment]
New release is ready: https://github.com/sunaku/dasht/releases/tag/v2.3.0 :gift:
