### ISSUE TITLE
ZSH completion

### ISSUE THREAD

**Issue by tmerse** [sunaku/dasht#10]
Thanks for this awesome plugin, this really improved my terminal based workflow.

I created a small zsh completion snippet. Maybe it is helpful.
https://gist.github.com/tmerse/851722c0c03cd442265ec523500c78c6

Created a pr for [oh-my-zsh](https://github.com/robbyrussell/oh-my-zsh) aswell.

Again, thanks for bringing dash to the linux commandline.

**Comment by sunaku** [comment]
Thanks for your contribution! :+1:

Should I add the snippet to the README or add it as a source-able file in the repo?

**Comment by tmerse** [comment]
I don't have any preference. 
You should go with what fits the project philosophy best (many features? unixy?).
I would see this in `README`-land though as shells may vary and It's rather far from core functionality.

**Comment by sunaku** [comment]
Cool, I'll create an `etc/` folder to house this snippet and add similar completion for BASH etc. :bulb:

**Comment by tmerse** [comment]
:thumbsup:

**Comment by sunaku** [comment]
Done in commit e294bcf7ede27be099bb59e3cb9bfb7da9ef3672 for _all_ dasht executables. :santa: Thanks again. :bow:
