### ISSUE TITLE
Font used in screenshots

### ISSUE THREAD

**Issue by alberteddu** [sunaku/dasht#11]
Hello — I'm sorry for creating an issue for this, but I can't seem to find another way to ask! 
Could you please tell me what font is used in the screenshot in the Readme for the terminal (and possibly also the color scheme? Although it looks like gruvbox)?

![terminal](https://raw.githubusercontent.com/sunaku/dasht/gh-pages/terminal.png)

**Comment by sunaku** [comment]
The font is [Tamzen](https://github.com/sunaku/tamzen-font) and the colorscheme is indeed gruvbox (but [my adaptation thereof](http://sunaku.github.io/gruvbox-terminal-color-scheme.html)). :santa: Cheers!

**Comment by alberteddu** [comment]
Thank you so much for sharing.
