### ISSUE TITLE
Provide a URL that will always return the latest stable version of dasht

### ISSUE THREAD

**Issue by lpil** [sunaku/dasht#13]
I would like to add dasht installation to the scripts I use to build a new machine. Currently this would be fiddly as I would have to keep updating this script when a new version is released.

**Comment by sunaku** [comment]
Try parsing the newest release tag from [this RSS feed](https://github.com/sunaku/dasht/tags.atom) and then resolve it to a download URL as follows:

    https://github.com/sunaku/dasht/archive/${newest_release_tag}.tar.gz

**Comment by lpil** [comment]
That's far too much work to comfortably do in ansible scripts, I'll use master.

**Comment by sunaku** [comment]
Can you run shell commands from Ansible?  If so, this ought to do the job:
```sh
wget -O dasht.tgz "https://github.com/sunaku/dasht/archive/$(
  wget -qO- 'https://github.com/sunaku/dasht/tags.atom' |
  grep '<title>' | sed -n '2s/ *<[^>]*>//gp'
).tar.gz"
```
Alternatively, contribute a dasht package to your favorite package manager.

**Comment by lpil** [comment]
Alas, Debian moves slowly. Thank you :)
