### ISSUE TITLE
Making forced install more specific

### ISSUE THREAD

**Issue by CrashyBang** [sunaku/dasht#18]
It is really hard to script the instillation of multiple doc-sets without being able to pass the `-y`.

I have tried setting up a script using `expect` but was getting no-where and I imagine this would be fairly easy to implement?

Thoughts?

Cheers.

**Comment by CrashyBang** [comment]
Sorry just found `-f` out of curiosity is there a more specific way to match terms, i.e. when I search `javascript` I get `AWS_Javascript` or `Javascript` and it installs both which is fine but would be nice if I could just get `javascript`

**Comment by sunaku** [comment]
The arguments passed into that script are, in fact, extended (and case-insensitive) regular expressions.  Therefore, you can match _just_ Javascript by writing `^javascript$`.  Refer to [the manual page](http://sunaku.github.io/dasht/man/man1/dasht-docsets-install.1.html) for details.

**Comment by CrashyBang** [comment]
Hey @sunaku you rock thank you :)
