### ISSUE TITLE
Non-standard confirmation prompt

### ISSUE THREAD

**Issue by mkaito** [sunaku/dasht#2]
Confirmation prompt is non-standard.

I'm talking about this particular passage:

```bash
echo "Install $docset docset" | xargs -p | grep -q . || continue # confirm
```

The current prompt feels noninformative and makes no mention that "something" is required for the answer to be positive.

You should adopt the commonly used `Do thing? [Y/n]` style. The capital `Y` means that an empty response will default to "yes". If appropriate, you can also use `[y/N]`, where the empty response would default to "no".

I haven't checked, but if there are other prompts in your code, please do the same about them.

I personally use the following function, which is written for ZSH, but it serves to illustrate:

```bash
function confirm()
{
    echo -n "$@ [y/N] "
    read answer
    for response in y Y yes YES Yes Sure sure SURE OK ok Ok kk; do
	[[ "_$answer" == "_$response" ]] && return 0
    done

    return 1
}
```

Just for illustration purposes, a positive-default version:

```bash
function negate()
{
    echo -n "$@ [Y/n] "
    read answer
    for response in n no No NO nope omgno; do
	[[ "_$answer" == "_$response" ]] && return 1
    done

    return 0
}
```

Usage as follows:

```bash
confirm "Do thing?" && do_thing
```

**Comment by sunaku** [comment]
Thanks for your suggestion.  Added `[y/N]` hint in ab82acf1162bb82ef95f95e59a35be14166598dd.
