### ISSUE TITLE
Mouse scrolling is lagging

### ISSUE THREAD

**Issue by mgroth0** [sunaku/dasht#21]
Mouse scrolling in any page I load is very laggy. I do not have this problem when use mouse scrolling in regular man pages. Also, I using the spacebar and b keys to navigate seems normal and is not lagging for me.

I'm on  OSX: 10.12.4 with dasht 2.1.0

**Comment by sunaku** [comment]
What do you mean by _page_?  Is it the web page you see upon following a search result link in w3m?

On my system, w3m version 0.5.3+git20170102 doesn't seem to provide any mouse scrolling support.  So the lag you observe might be an interaction between your terminal emulator's scrollback buffer and w3m.

As an alternative, you can use your regular graphical Web browser with dasht through `dasht-server`.

**Comment by sunaku** [comment]
Closing due to lack of response. :policeman: Please re-open if you still need help.
