### ISSUE TITLE
Unnecessary wget dependency on macOS

### ISSUE THREAD

**Issue by ilovezfs** [sunaku/dasht#24]
The wget dependency prevents the installation of dasht in Homebrew:
```
bash-3.2$ brew install dasht
Error: dasht contains conflicting version recursive dependencies:
  openssl, openssl@1.1
View these with `brew deps --tree dasht`.
bash-3.2$ brew deps --tree dasht
dasht
├── sqlite
│   └── readline
├── socat
│   ├── readline
│   └── openssl
├── wget
│   └── openssl@1.1
└── w3m
    ├── bdw-gc
    └── openssl
```
The best remedy here would be for dasht to use the system curl on macOS rather than wget.

**Comment by sunaku** [comment]
I chose wget because of its `-N` timestamping, `-T` timeout, and `-t` retries features that minimize network bandwidth when downloading docsets and lists thereof. :nerd_face:  Please submit a PR if you can implement the equivalent functionality with curl. :cake:

**Comment by sunaku** [comment]
Issue was resolved upstream at https://github.com/Homebrew/homebrew-core/pull/17255 so there's nothing more to do here.  Closing.
