### ISSUE TITLE
can't install Apple_Guides_and_Sample_Code docset

### ISSUE THREAD

**Issue by drselump14** [sunaku/dasht#27]
I'm trying to install apple guides and sample code which is the updated version of swift docs, but can't install it successfully. 

It always complains "mv: rename /Users/dr_selump14/.local/share/dasht/docsets/ to /Users/dr_selump14/.local/share/dasht/docsets/Apple_Guides_and_Sample_Code.docset: Invalid argument" 

Do you have any idea to fix this? thanks

**Comment by sunaku** [comment]
I tried installing it here but got a zero-length file downloaded instead:

```
echo Install Apple_Guides_and_Sample_Code docset [y/N] ?...y
--2017-09-17 12:36:58--  https://kapeli.com/feeds/Apple_Guides_and_Sample_Code.tgz
Resolving kapeli.com (kapeli.com)... 23.92.22.81
Connecting to kapeli.com (kapeli.com)|23.92.22.81|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 0 [application/x-tar]
Saving to: ‘/home/sunny/.local/share/dasht/docsets/Apple_Guides_and_Sample_Code.tgz’

Apple_Guides_and_Sample_Code.tgz            [ <=>                                                                           ]       0  --.-KB/s    in 0s

2017-09-17 12:36:59 (0.00 B/s) - ‘/home/sunny/.local/share/dasht/docsets/Apple_Guides_and_Sample_Code.tgz’ saved [0/0]


gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
exit 2
```

Can you check whether your dowloaded docset file is also zero-length?

```
-rw-r--r--. 1 sunny sunny 0 Oct 28  2016 Apple_Guides_and_Sample_Code.tgz
```

**Comment by drselump14** [comment]
Yeah, I got zero-length file too.... what happened actually?

**Comment by sunaku** [comment]
The docset is actually zero-length _upstream_ in Kapeli's repository:
https://kapeli.com/feeds/Apple_Guides_and_Sample_Code.tgz
Downstream users like us have no control over this. /cc @Kapeli

**Comment by Kapeli** [comment]
The Apple Guides and Sample Code docset has been removed. Apple no longer distributes it.

**Comment by drselump14** [comment]
Oh, OK .... that's too bad ... close this issue then
