### ISSUE TITLE
Error: too many options: "-line" ( sqlite3 )

### ISSUE THREAD

**Issue by joshpy** [sunaku/dasht#3]
I really like this project. 

One quick question : When I try a ./dasht,

I get the error Error : too many options: "-line" .

The version of sqlite3 I am using is 3.7.9 2011-11-01 00:52:41.

It looks like swapping the "$@" to be the first parameter of the sqlite3 command fixes this issue ( in the dasht-exec-query" ).

**Comment by sunaku** [comment]
Nice catch! :+1:  Fixed now in master branch at commit af51f618ab53e855a870b98999a9c78b406b2ea6.
