### ISSUE TITLE
Support to open index.html

### ISSUE THREAD

**Issue by an9wer** [sunaku/dasht#39]
Hi, I've just installed dasht on my computer, and it's awesome. But I've encountered some problems. 

I'd like to open `index.html` page first (e.g. `~/.local/share/dasht/docsets/Bash.docset/Contents/Resources/Documents/bash/index.html`) and then read docs by following the links in `index.html` page , but it seems like the `dasht` command only supports to search for pattern in docsets.

So I want to know is there a right way to do this?

**Comment by sunaku** [comment]
You can provide an empty query `''` to see the list of topics in the Bash docset by running:

```sh
$ dasht '' bash
```

Otherwise, if there is no search result for `index.html`, I don't know how you would do it.

It all depends on what's in the `bash.docset/Contents/Resources/docSet.dsidx` database.

**Comment by an9wer** [comment]
@sunaku Thanks for your reply! 

I've looked into the `docSet.dsidx` database and the `.docset` directory of Dash. I realized I had misunderstood it before.
