### ISSUE TITLE
Wrong URL

### ISSUE THREAD

**Issue by ghost** [sunaku/dasht#43]
When I try to search on dasht using `dasht 'server' rust` for example, then choose one of the link, press some spaces that expect to read some contents but it always end with this mesg:
```
The second edition of the book is no longer distributed with Rust's documentation.

If you came here via a link or web search, you may want to check out the current version of the book instead.

If you have an internet connection, you can find a copy distributed with Rust 1.30.
```

Why do we have this behavior?

**Comment by sunaku** [comment]
Sorry, this tool only searches/displays the contents of docsets and isn't responsible for their contents. :man_shrugging: Your question is best directed to the maintainer of the `rust` docset, which comes from [Dash for macOS](https://kapeli.com/dash#docsets).
