### ISSUE TITLE
dasht-server links not open

### ISSUE THREAD

**Issue by laoshaw** [sunaku/dasht#45]
after dasht-server started I can search in the browser just fine, but when I click the search results it does not open the URLs. Chrome says "Not allowed to load local resource: <URL>"

**Comment by sunaku** [comment]
This problem is described in `dasht-server` documentation, along with possible solutions, here:

> Browser refuses to load file:// links
http://sunaku.github.io/dasht/man/man1/dasht-server.1.html#browser-refuses-to-load-file-links

**Comment by laoshaw** [comment]
yes found that by reading your scripts. thanks.

**Comment by jb55** [comment]
why not rewrite links and serve files over http?

**Comment by MartyLake** [comment]
I second jb55. In windows 10, it is possible to use dasht in WSL, but the local links would not correspond to a valid windows path but a WSL path instead. Serving the files in http would solve this but would require parsing the sent html to also fix the paths included there in case the documentation also links to other pages directly.

**Comment by sunaku** [comment]
Now implemented in [the `issue-45` branch]( https://github.com/sunaku/dasht/tree/issue-45 ).  Please try it out and let me know if you find any problems.

**Comment by jb55** [comment]
works great!

**Comment by MartyLake** [comment]
it works !!!! thanks !

**Comment by sunaku** [comment]
Fix merged into `master` at commit 7b15337c925f338e97eafd8e0a9ac8b0d8f08435.
