### ISSUE TITLE
Option to create docsets from previously installed docsets

### ISSUE THREAD

**Issue by manitiwari9** [sunaku/dasht#46]
Option to create dasht docsets from previously installed docsets would be nice. Can someone guide what exactly is required for that to work?

**Comment by sunaku** [comment]
Which app did you originally use to install your previously installed docsets?

* If it was Dash for macOS, see https://github.com/sunaku/dasht/issues/15#issuecomment-332823536
* If it was Zeal, see https://www.reddit.com/r/commandline/comments/42f067/cza6x7k/

**Comment by sunaku** [comment]
Closing due to lack of response. :policeman: Please re-open if you still need help.
