### ISSUE TITLE
Open root rust guide?

### ISSUE THREAD

**Issue by tmpm697** [sunaku/dasht#47]
I installed  `rust` docset via: `dasht-docsets-install Rust`
I notice it include rust guide and search through, but how to open rust root guide like open firefox with url: https://doc.rust-lang.org/book/?

I want to issue `dasht <something> rust` and it open the rust book as open `https://doc.rust-lang.org/book/` in firefox, howto?

**Comment by tmpm697** [comment]
seem to be: `file:///home/user/.local/share/dasht/docsets/Rust.docset/Contents/Resources/Documents/doc.rust-lang.org/1.40.0/book/ch00-00-introduction.html#main`

**Comment by sunaku** [comment]
Yes, that appears to be correct. :heavy_check_mark:  You can also discover such URLs by running `dasht-server` and opening the local search engine in Firefox, where all search results will take you to the same kind of `file://` URLs.  See also [Browser refuses to load `file://` links](https://sunaku.github.io/dasht/man/man1/dasht-server.1.html#browser-refuses-to-load-file-links) in the `dasht-server` manual page.
