### ISSUE TITLE
Any chance to use an alternative terminal browser?

### ISSUE THREAD

**Issue by brglng** [sunaku/dasht#48]
Such as [browsh](https://www.brow.sh/)?

**Comment by sunaku** [comment]
Can `browsh` behave like a UNIX pager (by taking in the HTML to be displayed on `stdin`)?

Otherwise, we would need to write `dasht` search results to a temporary file every time. :thinking:

**Comment by brglng** [comment]
I think serving a web site at localhost may be a better idea, as `browsh` actually runs a headless Firefox at the background.

**Comment by sunaku** [comment]
Great! :+1:  Then `dasht-server` already solves this use-case (local search engine). :heavy_check_mark:  So I'm closing this issue. :checkered_flag:  Thanks!

```sh
$ dasht-server &
http://127.0.0.1:54321

$ browsh http://127.0.0.1:54321 
```
