### ISSUE TITLE
Unable to install python3 docset

### ISSUE THREAD

**Issue by denpy** [sunaku/dasht#55]
When running ```dasht-docsets-install python3``` I get the following error:

``` 
--2021-01-02 12:25:56--  https://api.github.com/repos/Kapeli/feeds/git/trees/
Resolving api.github.com (api.github.com)... 140.82.121.5
Connecting to api.github.com (api.github.com)|140.82.121.5|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-01-02 12:25:56 ERROR 404: Not Found.

Installable docsets (0):
```
Installing Bash with ```dasht-docsets-install bash``` worked fine.

**Comment by sunaku** [comment]
Thanks for reporting this issue.  It seems GitHub has changed their API, as I see this response:

```json
{
  "message": "Not Found",
  "documentation_url": "https://docs.github.com/rest/reference/git#get-a-tree"
}
```

**Comment by heckheckingheck** [comment]
I'm experiencing this same issue, is there any way I can help fix it?

**Comment by sunaku** [comment]
Okay, I found the root cause: there really is no docset named `python3` and  instead `Python_3` (with underscore) exists!

Please run either `dasht-docsets-install python_3` or `dasht-docsets-install python` and walk through the menu.

**Comment by denpy** [comment]
Thanks! Now it's working without any issues.
