### ISSUE TITLE
mv: cannot stat `~/.local/share/dasht/docsets/Express.docset': No such file or directory

### ISSUE THREAD

**Issue by netei** [sunaku/dasht#6]
When running the command `dasht-docsets-install express`

And pressing yes, I get the error specified in the title.

I'm using the latest master version (26ced75aced871e4ea7c618e5addd216f062c1fe)

After bisecting (with `rm ~/.local/share/dasht/docsets/Express.* -rf ; dasht-docsets-install express`), I found out the first bad commit : 540888544a5a5a1b1cbcbaac3af4976a3ffbaea5

I don't have any of the XDG env variables set ( `env | grep --color -E 'XDG' | wc -l` returns 0)

**Comment by netei** [comment]
The condition here : 

https://github.com/sunaku/dasht/commit/540888544a5a5a1b1cbcbaac3af4976a3ffbaea5#diff-fa4243a5cc4c7cbfbe63937ca8ca41edR64

Is causing the issue 

```test "$have" = "$want" || test -d "$want" && mv "$want" "$have"```

It seams strange to me but they doesn't seem to be any precedence here , for example If I do : 

`test "1" = "1" || echo "foo" && echo "bar"` 

I get "bar".

I think what you would like to do is : 

``````test "$have" = "$want" || { test -d "$want" && mv "$want" "$have" ; }```

**Comment by netei** [comment]
Maybe it is because my sh is symlinked to bash `ls -lah $(which sh)` , or is that on all machines the case nowadays ?

**Comment by sunaku** [comment]
Thanks for your bug report and fix! :+1:

:neckbeard: `/bin/sh` does not universally mean Bash.  For instance, in Debian and Ubuntu, it's [the Dash shell](https://wiki.ubuntu.com/DashAsBinSh).

**Comment by sunaku** [comment]
Fixed in master branch at commit 92fc97d42190915a45d9b25b3c732a19ec4fc42c. :bow:
