### ISSUE TITLE
Introduce exact match for dasht-docsets-install

### ISSUE THREAD

**Issue by netei** [sunaku/dasht#8]
When I do : 

`dasht-docsets-install -f Express`

Both Express and ExpressionEngine are installed.

Maybe we could introduce a flag --exact (-e) to tell dasht to only install exact matches (eg in my case, only Express, and not ExpressionEngine)

**Comment by netei** [comment]
Maybe `dasht-docsets-install -f '^Express$' is sufficient ?

**Comment by sunaku** [comment]
Yes, the latter is sufficient  :+1: and more powerful too :neckbeard: so there's no need for another option. :money_with_wings:

**Comment by netei** [comment]
Yep, that's what I ended up doing anyway !
