### ISSUE TITLE
dasht : Error: file is encrypted or is not a database

### ISSUE THREAD

**Issue by netei** [sunaku/dasht#9]
After installing the Javascript docset  ( dasht-docsets-install javascript)

I get the following error any time I run dasht (the error shows during 20ms, than my browser is launched as expected, but nothing in the Javascript docset can be loaded).

Do you know how I could inspect this ?

**Comment by sunaku** [comment]
Sounds like the docset archive was partially downloaded, extracted,
or corrupted.  I suggest that you remove and re-install the docset.

If you want to debug further, you can inspect the Javascript
docset's extracted SQLite3 database at
.local/share/dasht/docsets/JavaScript.docset/Contents/Resources/docSet.dsidx

In particular, try listing the names of all tables inside the database:

  $ sqlite3 PATH_TO_THE_DATABASE_FILE ".tables"

You should see something like this:

ZAPILANGUAGE  ZPARAMETER  Z_3DEPRECATEDININVERSE  ZCONTAINER
ZRETURNVALUE  Z_3INTRODUCEDININVERSE  ZDISTRIBUTIONVERSION  ZTOKEN
Z_3REMOVEDAFTERINVERSE  ZDOCSET  ZTOKENGROUP  Z_8RELATEDDOCSINVERSE
ZDOWNLOADABLEFILE  ZTOKENMETAINFORMATION  Z_8RELATEDNODESINVERSE
ZFILEPATH  ZTOKENTYPE  Z_8RELATEDSCINVERSE  ZHEADER
Z_14RELATEDGROUPS  Z_METADATA  ZNODE  Z_14RELATEDTOKENSINVERSE
Z_MODELCACHE  ZNODEURL  Z_1NODES  Z_PRIMARYKEY  ZNODEUUID
Z_2ADOPTEDBY  ZORDEREDSUBNODE  Z_2SUBCLASSEDBY

Alternatively, you can enable shell script tracing by appending "x"
to the very first line of the dasht-query-exec script, as follows:

  #!/bin/sh -ex

That prints all commands that were run until the point of failure.

**Comment by netei** [comment]
sqlite3 ~/.local/share/dasht/docsets/JavaScript.docset/Contents/Resources/docSet.dsidx ".tables"

gives : 

Error: file is encrypted or is not a database


Do you know where I can contact the person that uploaded that docset, to tell him that it is corrupted ?

**Comment by sunaku** [comment]
The problem seems more likely to be on your system:
did you try removing and re-installing that docset?

**Comment by netei** [comment]
Yes I tried to remove the docset and install it again.

The size of the file is  339968 bytes 

Running : 

```
$ ls -l ~/.local/share/dasht/docsets/JavaScript.docset/Contents/Resources/docSet.dsidx
-rw-r--r-- 1 hipped Domain Users 339968 Apr  4 05:15 /home/ldap/hipped/.local/share/dasht/docsets/JavaScript.docset/Contents/Resources/docSet.dsidx
```

**Comment by sunaku** [comment]
On Fri, 15 Apr 2016 00:03:02 -0700, netei wrote:
> Yes I tried to remove the docset and install it again.

Did you run `dasht-docsets-remove -f "^javascript$"` to remove it?
Or did you manually delete the extracted docset (which isn't enough)?

Try running these commands to make sure it's reinstalled properly:

    dasht-docsets-remove -f "^javascript$"
    dasht-docsets-install -f "^javascript$"

> The size of the file is  339968 bytes

It's larger (1593344 bytes) and newer (Apr 14 10:13) on my system.

**Comment by edi9999** [comment]
Indeed, it seems fixed now. You can close it now
